//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBlog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblText
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int adminId { get; set; }
        public int categoryId { get; set; }
    
        public virtual tblAdmins tblAdmins { get; set; }
        public virtual tblCategories tblCategories { get; set; }
    }
}
